name: Test Upload Result
description: Test Upload Result

inputs:
  os:
    description: 'The operating system to use'
    required: true
  architecture:
    description: 'The architecture to use'
    required: true
  runtime-type:
    description: 'Values: "dotnet", "mono", "fx"'
    required: true
  target_framework:
    description: 'The target framework to use'
    required: false
  build_configuration:
    description: 'The build configuration to use'
    required: true
  experimental:
    description: 'Whether the tests are mandatory for the build to pass'
    required: true

runs:
  using: "composite"
  steps:
    # Debug step to find TRX files before upload
    - name: Find TRX files (Windows)
      if: runner.os == 'Windows'
      run: |
        Write-Host "Finding TRX files before upload (Windows)..."
        if (Test-Path -Path "TestResults") {
          $files = Get-ChildItem -Path "TestResults" -Filter "*.trx" -File
          Write-Host "Found $($files.Count) TRX files in TestResults directory:"
          $files | ForEach-Object { Write-Host $_.Name }
        } else {
          Write-Host "TestResults directory not found"
        }
      shell: pwsh

    - name: Find TRX files (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "Finding TRX files before upload (Unix)..."
        if [ -d "TestResults" ]; then
          FILES=$(find TestResults -maxdepth 1 -name "*.trx" -type f)
          COUNT=$(find TestResults -maxdepth 1 -name "*.trx" -type f | wc -l)
          echo "Found $COUNT TRX files in TestResults directory:"
          echo "$FILES"
        else
          echo "TestResults directory not found"
        fi
      shell: bash

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: ${{(inputs.experimental == 'true' && 'experimental-') || ''}}test-results-${{inputs.runtime-type}}-${{inputs.os}}-${{inputs.architecture}}${{inputs.target_framework && format('-{0}', inputs.target_framework) || ''}}-${{inputs.build_configuration}}
        path: |
          TestResults/*.trx
        if-no-files-found: warn
        retention-days: 1
        compression-level: 0
