name: Test Upload Result
description: Test Upload Result

inputs:
  os:
    description: 'The operating system to use'
    required: true
  architecture:
    description: 'The architecture to use'
    required: true
  runtime-type:
    description: 'Values: "dotnet", "mono", "fx"'
    required: true
  target_framework:
    description: 'The target framework to use'
    required: false
  build_configuration:
    description: 'The build configuration to use'
    required: true
  experimental:
    description: 'Whether the tests are mandatory for the build to pass'
    required: true
    #type: boolean # We don't have boolean types in composites https://github.com/actions/runner/issues/2238

runs:
  using: "composite"
  steps:
    - name: Check for TRX files and validate test results
      id: check-trx
      run: |
        trx_files=$(find . -name "*.trx" -type f)
        if [ -z "$trx_files" ]; then
          echo "No TRX files found"
          echo "files-found=false" >> $GITHUB_OUTPUT
          echo "valid-results=false" >> $GITHUB_OUTPUT
        else
          echo "TRX files found:"
          echo "$trx_files"
          echo "files-found=true" >> $GITHUB_OUTPUT
          
          # Check if any TRX file has actual test results (total > 0)
          valid_found=false
          for file in $trx_files; do
            if [ -f "$file" ]; then
              total_count=$(grep -o 'total="[0-9]*"' "$file" | head -1 | grep -o '[0-9]*' || echo "0")
              echo "File $file has $total_count total tests"
              if [ "$total_count" -gt 0 ]; then
                valid_found=true
                break
              fi
            fi
          done
          
          if [ "$valid_found" = true ]; then
            echo "valid-results=true" >> $GITHUB_OUTPUT
          else
            echo "All TRX files have 0 tests - likely due to runtime issues"
            echo "valid-results=false" >> $GITHUB_OUTPUT
          fi
        fi
      shell: bash
      if: ${{success() || failure()}}
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{(success() || failure()) && steps.check-trx.outputs.files-found == 'true'}}
      with:
        name: ${{(inputs.experimental == 'true' && 'experimental-') || ''}}test-results-${{inputs.runtime-type}}-${{inputs.os}}-${{inputs.architecture}}${{inputs.target_framework && format('-{0}', inputs.target_framework) || ''}}-${{inputs.build_configuration}}
        path: '**/*.trx'
        if-no-files-found: ignore
        compression-level: 0
        
    - name: Log test result validation
      run: |
        if [ "${{steps.check-trx.outputs.valid-results}}" = "false" ]; then
          echo "⚠️ Warning: TRX files found but contain 0 tests. This may indicate runtime dependency issues."
          echo "This could cause empty test results in the final report."
        fi
      shell: bash
      if: ${{(success() || failure()) && steps.check-trx.outputs.files-found == 'true'}}