name: Setup .NET
description: Setup .NET using the provided target framework and architecture

inputs:
  architecture:
    description: 'The .NET architecture to setup'
    required: true
  target_framework:
    description: 'The .NET target framework to setup'
    required: true
  target_framework_array:
    description: 'The .NET target frameworks to setup'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET Sdk
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.101'

    - name: Get .NET Channels
      uses: ./.github/actions/get-dotnet-channel
      id: get_channels
      with:
        target_framework: ${{inputs.target_framework}}
        target_framework_array: ${{inputs.target_framework_array}}

    - name: Setup .NET SDK and Runtimes
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
          7.0.x
          6.0.x
          5.0.x
          3.1.x
          3.0.x
