<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
    <AssemblyName>HarmonyCompatibility.Host</AssemblyName>
    <RollForward>LatestPatch</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Targets/Targets.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
  </ItemGroup>
</Project>
