name: Setup .NET Windows
description: Setup .NET for Windows using the provided target framework and architecture

inputs:
  architecture:
    description: 'The .NET architecture to setup'
    required: true
  target_framework:
    description: 'The .NET target framework to setup'
    required: true
  target_framework_array:
    description: 'The .NET target frameworks to setup'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get .NET Channel for ${{inputs.target_framework}}
      uses: ./.github/actions/get-dotnet-channel
      id: get_channel
      with:
        target_framework: ${{inputs.target_framework}}
        target_framework_array: ${{inputs.target_framework_array}}

    - name: Get Program Files path for ${{inputs.architecture}}
      uses: ./.github/actions/get-program-files
      id: get-program-files
      with:
        architecture: ${{inputs.architecture}}

    - name: Setup .NET SDK and Runtimes ${{inputs.architecture}}
      run: |
        Invoke-WebRequest 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1;
        
        # Install all required .NET runtime versions
        $versions = @('9.0', '8.0', '7.0', '6.0', '5.0', '3.1', '3.0');
        foreach ($version in $versions) {
          Write-Host "Installing .NET $version runtime for ${{inputs.architecture}}";
          .\dotnet-install.ps1 -Runtime dotnet -SkipNonVersionedFiles -NoPath -Channel $version -Architecture ${{inputs.architecture}} -InstallDir "${{steps.get-program-files.outputs.path}}/dotnet";
        }
      shell: pwsh
